-- Freixo CRM MVP — PostgreSQL/Supabase
create extension if not exists pgcrypto;
create type public.app_role as enum ('admin','commercial');
create type public.client_status as enum ('active','inactive','potential','suspended','lost');
create type public.activity_kind as enum ('visit','call','meeting','email','task','note','opportunity','proposal','document','status_change');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text not null, role app_role not null default 'commercial', active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.role_permissions (role app_role not null, permission text not null, allowed boolean not null default true, primary key (role, permission));
insert into public.role_permissions (role, permission) values
  ('admin','users.manage'), ('admin','clients.all'), ('admin','workflow.all'), ('admin','audit.read'),
  ('commercial','clients.own'), ('commercial','workflow.own'), ('commercial','emails.own');
create table public.clients (id uuid primary key default gen_random_uuid(), code text not null unique, trade_name text not null, legal_name text, tax_id text, status client_status not null default 'potential', country text, region text, city text, address text, postal_code text, phone text, email text, website text, segment text, zone text, sales_channel text, priority smallint check(priority between 1 and 5), commercial_potential numeric(14,2), conditions text, notes text, last_visit_at timestamptz, last_contact_at timestamptz, next_contact_at timestamptz, owner_id uuid references public.profiles(id), created_by uuid not null references public.profiles(id), archived_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.client_contacts (id uuid primary key default gen_random_uuid(), client_id uuid not null references public.clients(id), first_name text not null, last_name text, job_title text, department text, email text, phone text, whatsapp text, is_primary boolean default false, communication_preference text, communication_consent boolean default false, active boolean default true, notes text, created_at timestamptz default now());
create table public.tasks (id uuid primary key default gen_random_uuid(), title text not null, description text, client_id uuid references public.clients(id), contact_id uuid references public.client_contacts(id), assignee_id uuid not null references public.profiles(id), created_by uuid not null references public.profiles(id), priority smallint not null default 3 check(priority between 1 and 5), due_at timestamptz, status text not null default 'open', result text, completed_at timestamptz, reminder_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.opportunity_stages (id uuid primary key default gen_random_uuid(), name text not null unique, position integer not null, probability smallint not null check(probability between 0 and 100), terminal boolean default false);
create table public.opportunities (id uuid primary key default gen_random_uuid(), client_id uuid not null references public.clients(id), contact_id uuid references public.client_contacts(id), seller_id uuid not null references public.profiles(id), stage_id uuid not null references public.opportunity_stages(id), title text not null, description text, estimated_value numeric(14,2) not null default 0, probability smallint check(probability between 0 and 100), expected_close date, source text, next_action text, loss_reason text, competitor text, notes text, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.visits (id uuid primary key default gen_random_uuid(), client_id uuid not null references public.clients(id), contact_id uuid references public.client_contacts(id), seller_id uuid not null references public.profiles(id), scheduled_at timestamptz not null, started_at timestamptz, completed_at timestamptz, visit_type text not null, status text not null default 'planned', location text, objective text, summary text, needs text, next_actions text, follow_up_at timestamptz, created_by uuid not null references public.profiles(id), created_at timestamptz default now(), updated_at timestamptz default now());
create table public.emails (id uuid primary key default gen_random_uuid(), client_id uuid references public.clients(id), opportunity_id uuid references public.opportunities(id), sender_id uuid not null references public.profiles(id), subject text not null, body_html text not null, status text not null default 'draft', graph_message_id text, error_code text, sent_at timestamptz, created_at timestamptz default now());
create table public.email_recipients (id uuid primary key default gen_random_uuid(), email_id uuid not null references public.emails(id) on delete cascade, contact_id uuid references public.client_contacts(id), address text not null, recipient_type text not null check(recipient_type in ('to','cc','bcc')));
create table public.activities (id uuid primary key default gen_random_uuid(), client_id uuid not null references public.clients(id), kind activity_kind not null, actor_id uuid not null references public.profiles(id), entity_id uuid, summary text not null, result text, occurred_at timestamptz not null default now(), created_at timestamptz default now());
create table public.audit_logs (id bigint generated always as identity primary key, actor_id uuid references public.profiles(id), action text not null, entity_type text not null, entity_id uuid, before_data jsonb, after_data jsonb, ip_hash text, created_at timestamptz default now());

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles (id,full_name,role,active) values (new.id,coalesce(new.raw_user_meta_data->>'full_name',new.raw_user_meta_data->>'name',new.email,'Utilizador'),case when not exists(select 1 from public.profiles) then 'admin'::public.app_role else 'commercial'::public.app_role end,true) on conflict(id) do update set full_name=excluded.full_name,updated_at=now(); return new; end; $$;
create trigger on_auth_user_created after insert or update of email on auth.users for each row execute procedure public.handle_new_user();

create index clients_search_idx on public.clients using gin (to_tsvector('simple', coalesce(trade_name,'') || ' ' || coalesce(code,'') || ' ' || coalesce(tax_id,'')));
create index clients_owner_idx on public.clients(owner_id) where archived_at is null;
create index activities_client_date_idx on public.activities(client_id, occurred_at desc);
create index tasks_assignee_due_idx on public.tasks(assignee_id, due_at) where completed_at is null;
create index opportunities_seller_stage_idx on public.opportunities(seller_id, stage_id);

alter table public.profiles enable row level security; alter table public.role_permissions enable row level security; alter table public.clients enable row level security; alter table public.client_contacts enable row level security; alter table public.tasks enable row level security; alter table public.opportunities enable row level security; alter table public.visits enable row level security; alter table public.emails enable row level security; alter table public.email_recipients enable row level security; alter table public.activities enable row level security; alter table public.audit_logs enable row level security;

create or replace function public.current_role() returns app_role language sql stable security definer set search_path=public as $$ select role from profiles where id=auth.uid() and active=true $$;
create policy "profiles self or admin" on public.profiles for select using (id=auth.uid() or public.current_role()='admin');
create policy "profiles admin manage" on public.profiles for all using (public.current_role()='admin') with check (public.current_role()='admin');
create policy "permissions authenticated read" on public.role_permissions for select using (auth.uid() is not null);
create policy "permissions admin manage" on public.role_permissions for all using (public.current_role()='admin') with check (public.current_role()='admin');
create policy "clients authorized read" on public.clients for select using (owner_id=auth.uid() or public.current_role()='admin');
create policy "clients authorized write" on public.clients for all using (owner_id=auth.uid() or public.current_role()='admin') with check (owner_id=auth.uid() or public.current_role()='admin');
create policy "contacts follow client" on public.client_contacts for all using (exists(select 1 from public.clients c where c.id=client_id and (c.owner_id=auth.uid() or public.current_role()='admin')));
create policy "tasks authorized" on public.tasks for all using (assignee_id=auth.uid() or created_by=auth.uid() or public.current_role()='admin');
create policy "opportunities authorized" on public.opportunities for all using (seller_id=auth.uid() or public.current_role()='admin');
create policy "visits authorized" on public.visits for all using (seller_id=auth.uid() or public.current_role()='admin');
create policy "emails authorized" on public.emails for all using (sender_id=auth.uid() or public.current_role()='admin');
create policy "email recipients follow email" on public.email_recipients for all using (exists(select 1 from public.emails e where e.id=email_id and (e.sender_id=auth.uid() or public.current_role()='admin'))) with check (exists(select 1 from public.emails e where e.id=email_id and (e.sender_id=auth.uid() or public.current_role()='admin')));
create policy "activities via client" on public.activities for select using (exists(select 1 from public.clients c where c.id=client_id and (c.owner_id=auth.uid() or public.current_role()='admin')));
create policy "activities authorized insert" on public.activities for insert with check (actor_id=auth.uid() and exists(select 1 from public.clients c where c.id=client_id and (c.owner_id=auth.uid() or public.current_role()='admin')));
create policy "audit admin read" on public.audit_logs for select using (public.current_role()='admin');
