"use client";

import { useEffect, useMemo, useState } from "react";
import type { Session } from "@supabase/supabase-js";
import { supabase } from "./supabase";
import EmailComposer, { type ComposedEmail } from "./email-composer";

export type DossierClient = {
  id?: string; code: string; name: string; city: string; email: string; phone?: string; taxId?: string; owner: string; status: string; priority: string;
  segment?: string; potential?: string; cecofersa?: boolean; lasRias?: boolean; factorPro?: boolean; bigMat?: boolean; industrialPro?: boolean; address?: string; postalCode?: string; region?: string; visitFrequency?: string;
  nextAction?: string; nextActionDate?: string; growthPlan?: string; notes?: string; referenceName?: string; last?: string;
  contacts?: Array<{ id: string; name: string; jobTitle: string; email: string; phone: string; isPrimary: boolean }>;
  manufacturers?: Array<{ id?: string; relationId?: string; name: string; code: string; discount: number | null; discountStatus: string }>;
};

type Interaction = {
  id: string; type: string; occurredAt: string; manufacturerId: string; manufacturer: string; contactId: string; contact: string;
  subject: string; description: string; result: string; nextAction: string; nextActionDate: string; authorId: string; author: string; status: string;
};

const interactionTypes = ["Email","Chamada telefónica","WhatsApp","Visita comercial","Reunião","Videoconferência","Proposta enviada","Orçamento enviado","Envio de catálogo","Envio de tabela de preços","Pedido de cotação","Consulta recebida","Seguimento / Follow-up","Reclamação","Amostra enviada","Encomenda","Informação técnica","Nota interna","Outra interação"];
const results = ["Positivo","Neutro","Negativo","Aguarda resposta","Concluído","Sem resposta"];
const kindFor = (type: string) => type === "Email" ? "email" : type.includes("Chamada") ? "call" : type.includes("Visita") ? "visit" : type.includes("Reunião") || type.includes("Videoconferência") ? "meeting" : type.includes("Proposta") ? "proposal" : "note";

export default function ClientDossier({ client, session, providerToken, isAdmin, onClose, onUpdate }: { client: DossierClient; session: Session | null; providerToken: string | null; isAdmin: boolean; onClose:()=>void; onUpdate:(client:DossierClient)=>void }) {
  const [record,setRecord]=useState(client);
  const [interactions,setInteractions]=useState<Interaction[]>([]);
  const [mode,setMode]=useState<"view"|"edit"|"interaction"|"email">("view");
  const [editingInteraction,setEditingInteraction]=useState<Interaction|null>(null);
  const [notice,setNotice]=useState("");
  const [savingClient,setSavingClient]=useState(false);
  const [editingContact,setEditingContact]=useState<NonNullable<DossierClient["contacts"]>[number]|null>(null);
  const [contactFormOpen,setContactFormOpen]=useState(false);
  const [contactDraft,setContactDraft]=useState({name:"",email:"",phone:"",jobTitle:""});
  const [historyQuery,setHistoryQuery]=useState("");
  const [typeFilter,setTypeFilter]=useState("");
  const [manufacturerFilter,setManufacturerFilter]=useState("");
  const [commercialFilter,setCommercialFilter]=useState("");
  const [dateFrom,setDateFrom]=useState(""); const [dateTo,setDateTo]=useState("");

  const loadInteractions=async()=>{
    if(!record.id)return;
    const {data,error}=await supabase.from("activities").select("id,interaction_type,occurred_at,manufacturer_id,contact_id,subject,description,result,next_action,next_action_date,actor_id,status,manufacturers(name),client_contacts(first_name,last_name),profiles!activities_actor_id_fkey(full_name)").eq("client_id",record.id).neq("kind","task").order("occurred_at",{ascending:false});
    if(error){setNotice(error.message);return;}
    setInteractions((data??[]).map((row:any)=>({id:row.id,type:row.interaction_type,occurredAt:row.occurred_at,manufacturerId:row.manufacturer_id??"",manufacturer:row.manufacturers?.name??"",contactId:row.contact_id??"",contact:[row.client_contacts?.first_name,row.client_contacts?.last_name].filter(Boolean).join(" "),subject:row.subject??"",description:row.description??"",result:row.result??"",nextAction:row.next_action??"",nextActionDate:row.next_action_date??"",authorId:row.actor_id,author:row.profiles?.full_name??"Utilizador",status:row.status??"completed"})));
  };
  useEffect(()=>{loadInteractions();},[record.id]);

  const filtered=useMemo(()=>interactions.filter(item=>{
    const text=`${item.subject} ${item.description} ${item.type} ${item.manufacturer} ${item.contact} ${item.author}`.toLowerCase();
    const day=item.occurredAt.slice(0,10);
    return text.includes(historyQuery.toLowerCase())&&(!typeFilter||item.type===typeFilter)&&(!manufacturerFilter||item.manufacturer===manufacturerFilter)&&(!commercialFilter||item.author===commercialFilter)&&(!dateFrom||day>=dateFrom)&&(!dateTo||day<=dateTo);
  }),[interactions,historyQuery,typeFilter,manufacturerFilter,commercialFilter,dateFrom,dateTo]);
  const groups=useMemo(()=>{const map=new Map<string,Interaction[]>();for(const item of filtered){const key=item.occurredAt.slice(0,7);map.set(key,[...(map.get(key)??[]),item]);}return [...map.entries()].sort(([a],[b])=>b.localeCompare(a));},[filtered]);
  const lastInteraction=interactions[0];
  const nextDated=interactions.filter(x=>x.nextAction&&x.nextActionDate).sort((a,b)=>a.nextActionDate.localeCompare(b.nextActionDate))[0];

  const saveClient=async(event:React.FormEvent<HTMLFormElement>)=>{
    event.preventDefault(); if(!record.id){setNotice("Este cliente ainda não tem um registo válido na base de dados. Feche a ficha e volte a criá-lo.");return;} const form=new FormData(event.currentTarget);
    const payload={trade_name:String(form.get("name")),tax_id:String(form.get("taxId")||"")||null,segment:String(form.get("segment")||"")||null,potential:String(form.get("potential")||"")||null,priority_label:String(form.get("priority")||"")||null,commercial_name:String(form.get("owner")||"")||null,status:String(form.get("status"))==="Ativo"?"active":"potential",validation_status:String(form.get("status"))==="A validar"?"a_validar":null,visit_frequency:String(form.get("visitFrequency")||"")||null,next_action:String(form.get("nextAction")||"")||null,next_contact_at:String(form.get("nextActionDate")||"")||null,growth_plan:String(form.get("growthPlan")||"")||null,notes:String(form.get("notes")||"")||null,email:String(form.get("email")||"")||null,phone:String(form.get("phone")||"")||null,address:String(form.get("address")||"")||null,postal_code:String(form.get("postalCode")||"")||null,city:String(form.get("city")||"")||null,region:String(form.get("region")||"")||null,is_cecofersa_member:form.get("cecofersa")==="on",is_las_rias_member:form.get("lasRias")==="on",is_factor_pro_member:form.get("factorPro")==="on",is_big_mat_member:form.get("bigMat")==="on",is_industrial_pro_member:form.get("industrialPro")==="on",updated_at:new Date().toISOString()};
    setSavingClient(true);setNotice("");
    const {data,error}=await supabase.from("clients").update(payload).eq("id",record.id).select("id,trade_name").single(); setSavingClient(false); if(error||!data){setNotice(`Não foi possível guardar as alterações: ${error?.message??"o registo não foi atualizado"}`);return;}
    const updated={...record,name:payload.trade_name,taxId:payload.tax_id??"",segment:payload.segment??"",potential:payload.potential??"",priority:payload.priority_label??"",owner:payload.commercial_name??"",status:String(form.get("status")),visitFrequency:payload.visit_frequency??"",nextAction:payload.next_action??"",nextActionDate:String(form.get("nextActionDate")||""),growthPlan:payload.growth_plan??"",notes:payload.notes??"",email:payload.email??"",phone:payload.phone??"",address:payload.address??"",postalCode:payload.postal_code??"",city:payload.city??"",region:payload.region??"",cecofersa:payload.is_cecofersa_member,lasRias:payload.is_las_rias_member,factorPro:payload.is_factor_pro_member,bigMat:payload.is_big_mat_member,industrialPro:payload.is_industrial_pro_member}; setRecord(updated);onUpdate(updated);setMode("view");setNotice("Ficha atualizada com sucesso.");
  };

  const saveInteraction=async(event:React.FormEvent<HTMLFormElement>)=>{
    event.preventDefault(); if(!record.id||!session)return; const form=new FormData(event.currentTarget); const date=String(form.get("date"));const time=String(form.get("time"));const type=String(form.get("type"));
    const payload={client_id:record.id,kind:kindFor(type),interaction_type:type,occurred_at:new Date(`${date}T${time}`).toISOString(),start_at:new Date(`${date}T${time}`).toISOString(),manufacturer_id:String(form.get("manufacturer")||"")||null,contact_id:String(form.get("contact")||"")||null,title:String(form.get("subject")),subject:String(form.get("subject")),summary:String(form.get("subject")),description:String(form.get("description")||"")||null,result:String(form.get("result")||"")||null,next_action:String(form.get("nextAction")||"")||null,next_action_date:String(form.get("nextActionDate")||"")||null,actor_id:session.user.id,assigned_to:session.user.id,source_module:"client",status:"completed",updated_at:new Date().toISOString()};
    const response=editingInteraction?await supabase.from("activities").update(payload).eq("id",editingInteraction.id):await supabase.from("activities").insert(payload);if(response.error){setNotice(response.error.message);return;}setMode("view");setEditingInteraction(null);setNotice(editingInteraction?"Interação atualizada.":"Interação registada no histórico.");await loadInteractions();
  };

  const recordEmail=async(email:ComposedEmail)=>{if(!record.id||!session)throw new Error("A sessão terminou.");const sentAt=new Date().toISOString();const saved=await supabase.from("emails").insert({client_id:record.id,sender_id:session.user.id,subject:email.subject,body_html:email.bodyHtml,status:"sent",sent_at:sentAt}).select("id,sent_at").single();if(saved.error)throw saved.error;const recipients=[{email_id:saved.data.id,address:email.to,recipient_type:"to"},...email.cc.map(address=>({email_id:saved.data.id,address,recipient_type:"cc"}))];const recipientResult=await supabase.from("email_recipients").insert(recipients);if(recipientResult.error)throw recipientResult.error;await supabase.from("activities").insert({client_id:record.id,kind:"email",interaction_type:"Email",actor_id:session.user.id,entity_id:saved.data.id,subject:email.subject,summary:`Email enviado: ${email.subject}`,description:email.attachments.length?`${email.bodyText}\n\nAnexos: ${email.attachments.map(file=>file.name).join(", ")}`:email.bodyText,result:`Para ${email.to}${email.cc.length?` · CC: ${email.cc.join("; ")}`:""}`,status:"sent",occurred_at:sentAt});setMode("view");setNotice("Email enviado e registado automaticamente.");await loadInteractions()};

  const openContactForm=(contact?:NonNullable<DossierClient["contacts"]>[number])=>{setEditingContact(contact??null);setContactDraft(contact?{name:contact.name,email:contact.email,phone:contact.phone,jobTitle:contact.jobTitle}:{name:"",email:"",phone:"",jobTitle:""});setContactFormOpen(true);setNotice("");};
  const saveContact=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!record.id||!contactDraft.name.trim())return;const payload={first_name:contactDraft.name.trim(),last_name:null,email:contactDraft.email.trim()||null,phone:contactDraft.phone.trim()||null,job_title:contactDraft.jobTitle.trim()||null,active:true};const response=editingContact?await supabase.from("client_contacts").update(payload).eq("id",editingContact.id).select("id").single():await supabase.from("client_contacts").insert({...payload,client_id:record.id}).select("id").single();if(response.error||!response.data){setNotice(`Não foi possível guardar o contacto: ${response.error?.message??"erro desconhecido"}`);return;}const saved={id:response.data.id,name:contactDraft.name.trim(),email:contactDraft.email.trim(),phone:contactDraft.phone.trim(),jobTitle:contactDraft.jobTitle.trim(),isPrimary:editingContact?.isPrimary??false};const contacts=editingContact?(record.contacts??[]).map(item=>item.id===saved.id?saved:item):[...(record.contacts??[]),saved];const updated={...record,contacts};setRecord(updated);onUpdate(updated);setContactFormOpen(false);setEditingContact(null);setNotice(editingContact?"Contacto atualizado com sucesso.":"Contacto adicionado com sucesso.");};
  const removeContact=async(contact:NonNullable<DossierClient["contacts"]>[number])=>{if(!isAdmin||!confirm(`Remover o contacto “${contact.name}”? O histórico associado será preservado.`))return;const {data,error}=await supabase.from("client_contacts").update({active:false}).eq("id",contact.id).select("id").single();if(error||!data){setNotice(`Não foi possível remover o contacto: ${error?.message??"registo não atualizado"}`);return;}const updated={...record,contacts:(record.contacts??[]).filter(item=>item.id!==contact.id)};setRecord(updated);onUpdate(updated);setNotice("Contacto removido. O histórico foi preservado.");};
  const editManufacturer=async(item:NonNullable<DossierClient["manufacturers"]>[number])=>{if(!item.relationId)return;const code=prompt("Código de cliente no fabricante",item.code);if(code===null)return;const discount=prompt("Desconto acordado (ex.: 0.25 para 25%). Deixe vazio por confirmar.",item.discount===null?"":String(item.discount));if(discount===null)return;const discountStatus=prompt("Estado do desconto",item.discountStatus);if(discountStatus===null)return;const {error}=await supabase.from("client_manufacturers").update({manufacturer_client_code:code||null,agreed_discount:discount===""?null:Number(discount),discount_status:discountStatus||null,updated_at:new Date().toISOString()}).eq("id",item.relationId);if(error){setNotice(error.message);return;}const manufacturers=record.manufacturers?.map(x=>x.relationId===item.relationId?{...x,code,discount:discount===""?null:Number(discount),discountStatus}:x);const updated={...record,manufacturers};setRecord(updated);onUpdate(updated);};
  const addManufacturer=async()=>{if(!record.id)return;const name=prompt("Nome exato do fabricante/marca");if(!name)return;let {data:manufacturer}=await supabase.from("manufacturers").select("id,name").ilike("name",name).maybeSingle();if(!manufacturer&&isAdmin){const created=await supabase.from("manufacturers").insert({name}).select("id,name").single();if(created.error){setNotice(created.error.message);return;}manufacturer=created.data;}if(!manufacturer){setNotice("Fabricante não encontrado. Um Administrador pode criá-lo.");return;}const created=await supabase.from("client_manufacturers").insert({client_id:record.id,manufacturer_id:manufacturer.id,discount_status:"A preencher"}).select("id").single();if(created.error){setNotice(created.error.message);return;}const manufacturers=[...(record.manufacturers??[]),{id:manufacturer.id,relationId:created.data.id,name:manufacturer.name,code:"",discount:null,discountStatus:"A preencher"}];const updated={...record,manufacturers};setRecord(updated);onUpdate(updated);};
  const deleteInteraction=async(item:Interaction)=>{if(!isAdmin||!confirm("Tem a certeza de que pretende eliminar esta interação?"))return;const {error}=await supabase.from("activities").delete().eq("id",item.id);if(error)setNotice(error.message);else await loadInteractions();};

  return <div className="client-detail-backdrop" onClick={onClose}><article className="client-detail dossier" onClick={e=>e.stopPropagation()}><button className="client-detail-close" onClick={onClose} aria-label="Fechar ficha">×</button>
    <div className="client-detail-title"><span>{record.code}</span><h2>{record.name}</h2><div className="association-badges">{[["cecofersa","SÓCIO CECOFERSA"],["lasRias","SÓCIO LAS RIAS"],["factorPro","SÓCIO FACTOR PRO / EL SÁBIO"],["bigMat","SÓCIO BIG MAT"],["industrialPro","SÓCIO INDUSTRIAL PRO"]].filter(([key])=>Boolean(record[key as keyof DossierClient])).map(([key,label])=><em className="cecofersa-badge" key={key}>{label}</em>)} <em className="status">{record.status}</em></div><div className="dossier-actions"><button onClick={()=>setMode("edit")}>Editar Cliente</button><button onClick={()=>setMode("email")}>Enviar Email</button><button className="primary" onClick={()=>{setEditingInteraction(null);setMode("interaction")}}>＋ Nova Interação</button></div></div>
    {notice&&<div className="email-notice" role="status">{notice}</div>}
    {mode==="edit"&&<form className="dossier-form" onSubmit={saveClient}><h3>Editar cliente</h3><div className="form-grid"><label>Nome<input name="name" defaultValue={record.name} required/></label><label>NIF<input name="taxId" defaultValue={record.taxId}/></label><label>Segmento<input name="segment" defaultValue={record.segment}/></label><label>Potencial<select name="potential" defaultValue={record.potential}><option/><option>Ouro</option><option>Prata</option><option>Bronze</option></select></label><label>Prioridade<select name="priority" defaultValue={record.priority}><option/><option>A</option><option>B</option><option>C</option></select></label><label>Comercial<select name="owner" defaultValue={record.owner}><option>Alexandre</option><option>Tina</option><option>Lúcia</option></select></label><label>Estado<select name="status" defaultValue={record.status}><option>Ativo</option><option>Potencial</option><option>A validar</option></select></label><label>Frequência de visita<input name="visitFrequency" defaultValue={record.visitFrequency}/></label><label>Email principal<input type="email" name="email" defaultValue={record.email}/></label><label>Telefone principal<input name="phone" defaultValue={record.phone}/></label><label>Morada<input name="address" defaultValue={record.address}/></label><label>Código postal<input name="postalCode" defaultValue={record.postalCode}/></label><label>Localidade<input name="city" defaultValue={record.city}/></label><label>Distrito/Província<input name="region" defaultValue={record.region}/></label><label>Próxima ação<input name="nextAction" defaultValue={record.nextAction}/></label><label>Data da próxima ação<input type="date" name="nextActionDate" defaultValue={record.nextActionDate}/></label><label className="full">Plano de crescimento<textarea name="growthPlan" defaultValue={record.growthPlan}/></label><label className="full">Observações<textarea name="notes" defaultValue={record.notes}/></label><fieldset className="association-selector full"><legend>Associações / Grupos Comerciais</legend><div><label className="check"><input type="checkbox" name="cecofersa" defaultChecked={record.cecofersa}/> Sócio CECOFERSA</label><label className="check"><input type="checkbox" name="lasRias" defaultChecked={record.lasRias}/> Sócio LAS RIAS</label><label className="check"><input type="checkbox" name="factorPro" defaultChecked={record.factorPro}/> Sócio FACTOR PRO / El Sábio</label><label className="check"><input type="checkbox" name="bigMat" defaultChecked={record.bigMat}/> Sócio BIG MAT</label><label className="check"><input type="checkbox" name="industrialPro" defaultChecked={record.industrialPro}/> Sócio INDUSTRIAL PRO</label></div></fieldset></div><div className="form-actions"><button type="button" onClick={()=>setMode("view")} disabled={savingClient}>Cancelar</button><button className="primary" disabled={savingClient}>{savingClient?"A guardar…":"Guardar alterações"}</button></div></form>}
    {mode==="interaction"&&<InteractionForm item={editingInteraction} client={record} onSubmit={saveInteraction} onCancel={()=>{setMode("view");setEditingInteraction(null)}}/>}
    {mode==="email"&&session&&<section className="dossier-form"><h3>Enviar email</h3><EmailComposer providerToken={providerToken} userId={session.user.id} initialTo={record.email} toOptions={[{label:record.name,email:record.email},...(record.contacts??[]).map(x=>({label:x.name,email:x.email}))]} onCancel={()=>setMode("view")} onSent={recordEmail}/></section>}
    {mode==="view"&&<><div className="dossier-summary"><div><span>Última interação</span><strong>{lastInteraction?`${new Date(lastInteraction.occurredAt).toLocaleDateString("pt-PT")} — ${lastInteraction.type}`:"Sem interações"}</strong></div><div className={nextDated&&nextDated.nextActionDate<new Date().toISOString().slice(0,10)?"overdue":""}><span>Próxima ação</span><strong>{nextDated?`${nextDated.nextAction} · ${new Date(nextDated.nextActionDate).toLocaleDateString("pt-PT")}`:record.nextAction||"Não definida"}</strong>{nextDated&&nextDated.nextActionDate<new Date().toISOString().slice(0,10)&&<em>Ação em atraso</em>}</div></div>
    <div className="client-detail-grid"><section><h3>Identificação</h3><p><b>NIF</b>{record.taxId||"—"}</p><p><b>Segmento</b>{record.segment||"—"}</p><p><b>Potencial</b>{record.potential||"—"}</p></section><section><h3>Classificação comercial</h3><p><b>Comercial</b>{record.owner}</p><p><b>Prioridade</b>{record.priority}</p><p><b>Estado</b>{record.status}</p></section><section><h3>Contacto principal</h3><p><b>Email</b>{record.email||"—"}</p><p><b>Telefone</b>{record.phone||"—"}</p><p><b>Referência</b>{record.referenceName||"—"}</p></section><section><h3>Morada</h3><p>{record.address||"—"}</p><p>{[record.postalCode,record.city].filter(Boolean).join(" ")||"—"}</p><p>{record.region||"—"}</p></section></div>
    <section className="client-detail-section"><div className="section-title"><h3>Contactos</h3><button onClick={()=>openContactForm()}>＋ Adicionar contacto</button></div>{contactFormOpen&&<form className="dossier-form contact-form" onSubmit={saveContact}><h3>{editingContact?"Editar contacto":"Novo contacto"}</h3><div className="form-grid"><label>Nome<input value={contactDraft.name} onChange={event=>setContactDraft({...contactDraft,name:event.target.value})} required/></label><label>Email<input type="email" value={contactDraft.email} onChange={event=>setContactDraft({...contactDraft,email:event.target.value})}/></label><label>Telemóvel<input type="tel" value={contactDraft.phone} onChange={event=>setContactDraft({...contactDraft,phone:event.target.value})}/></label><label>Cargo na empresa<input value={contactDraft.jobTitle} onChange={event=>setContactDraft({...contactDraft,jobTitle:event.target.value})}/></label></div><div className="form-actions"><button type="button" onClick={()=>{setContactFormOpen(false);setEditingContact(null)}}>Cancelar</button><button className="primary">Guardar contacto</button></div></form>}{record.contacts?.length?<div className="detail-table contacts-table"><div className="detail-head"><b>Nome</b><b>Email</b><b>Telemóvel</b><b>Cargo</b><b>Ações</b></div>{record.contacts.map(contact=><div key={contact.id}><strong>{contact.name}{contact.isPrimary?" · Principal":""}</strong><span>{contact.email||"—"}</span><span>{contact.phone||"—"}</span><span>{contact.jobTitle||"—"}</span><span className="contact-actions"><button onClick={()=>openContactForm(contact)}>Editar</button>{isAdmin&&<button className="danger" onClick={()=>removeContact(contact)}>Remover</button>}</span></div>)}</div>:<p>Sem contactos associados.</p>}</section>
    <section className="client-detail-section"><div className="section-title"><h3>Fabricantes / Marcas</h3><button onClick={addManufacturer}>＋ Associar fabricante</button></div>{record.manufacturers?.length?<div className="detail-table manufacturers-table"><div className="detail-head"><b>Fabricante</b><b>Código cliente</b><b>Desconto</b><b>Estado</b><b></b></div>{record.manufacturers.map(item=><div key={item.name}><strong>{item.name}</strong><span>{item.code||"—"}</span><span>{item.discount===null?"Por confirmar":new Intl.NumberFormat("pt-PT",{style:"percent",maximumFractionDigits:2}).format(item.discount)}</span><span>{item.discountStatus||"—"}</span><button onClick={()=>editManufacturer(item)}>Editar</button></div>)}</div>:<p>Sem fabricantes associados.</p>}</section>
    <section className="client-detail-section"><h3>Gestão comercial</h3><div className="client-detail-grid"><p><b>Frequência de visita</b>{record.visitFrequency||"—"}</p><p><b>Última visita</b>{record.last}</p><p><b>Próxima ação</b>{record.nextAction||"—"}</p><p><b>Plano de crescimento</b>{record.growthPlan||"—"}</p></div>{record.notes&&<p><b>Observações</b><br/>{record.notes}</p>}</section>
    <section className="client-detail-section history"><h3>Histórico de Interações</h3><div className="history-filters"><input placeholder="Pesquisar no histórico..." value={historyQuery} onChange={e=>setHistoryQuery(e.target.value)}/><select value={typeFilter} onChange={e=>setTypeFilter(e.target.value)}><option value="">Tipos: Todos</option>{interactionTypes.map(x=><option key={x}>{x}</option>)}</select><select value={manufacturerFilter} onChange={e=>setManufacturerFilter(e.target.value)}><option value="">Fabricantes: Todos</option>{record.manufacturers?.map(x=><option key={x.name}>{x.name}</option>)}</select><select value={commercialFilter} onChange={e=>setCommercialFilter(e.target.value)}><option value="">Comerciais: Todos</option>{[...new Set(interactions.map(x=>x.author))].map(x=><option key={x}>{x}</option>)}</select><input type="date" aria-label="Data inicial" value={dateFrom} onChange={e=>setDateFrom(e.target.value)}/><input type="date" aria-label="Data final" value={dateTo} onChange={e=>setDateTo(e.target.value)}/></div>{groups.length?groups.map(([month,items],index)=><details key={month} open={index===0}><summary>{new Intl.DateTimeFormat("pt-PT",{month:"long",year:"numeric"}).format(new Date(`${month}-02`))} — {items.length} {items.length===1?"interação":"interações"}</summary><div className="timeline">{items.map(item=><article key={item.id}><time>{new Date(item.occurredAt).toLocaleString("pt-PT")}</time><div><strong>{item.type}{item.manufacturer?` — ${item.manufacturer}`:""}</strong><h4>{item.subject}</h4><p>{item.description}</p><small>Registado por {item.author}{item.contact?` · ${item.contact}`:""}{item.result?` · ${item.result}`:""}</small>{item.nextAction&&<em>Próxima ação: {item.nextAction}{item.nextActionDate?` · ${new Date(item.nextActionDate).toLocaleDateString("pt-PT")}`:""}</em>}</div><aside>{(isAdmin||item.authorId===session?.user.id)&&<button onClick={()=>{setEditingInteraction(item);setMode("interaction")}}>Editar</button>}{isAdmin&&<button className="danger" onClick={()=>deleteInteraction(item)}>Eliminar</button>}</aside></article>)}</div></details>):<p>Não existem interações para os filtros selecionados.</p>}</section></>}
  </article></div>;
}

function InteractionForm({item,client,onSubmit,onCancel}:{item:Interaction|null;client:DossierClient;onSubmit:(event:React.FormEvent<HTMLFormElement>)=>void;onCancel:()=>void}){const now=new Date();return <form className="dossier-form" onSubmit={onSubmit}><h3>{item?"Editar interação":"Nova interação"}</h3><div className="form-grid"><label>Tipo<select name="type" defaultValue={item?.type??"Chamada telefónica"}>{interactionTypes.map(x=><option key={x}>{x}</option>)}</select></label><label>Data<input type="date" name="date" defaultValue={item?.occurredAt.slice(0,10)??now.toISOString().slice(0,10)} required/></label><label>Hora<input type="time" name="time" defaultValue={item?new Date(item.occurredAt).toTimeString().slice(0,5):now.toTimeString().slice(0,5)} required/></label><label>Fabricante<select name="manufacturer" defaultValue={item?.manufacturerId??""}><option value="">Sem fabricante específico</option>{client.manufacturers?.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Contacto<select name="contact" defaultValue={item?.contactId??""}><option value="">Sem contacto específico</option>{client.contacts?.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Resultado<select name="result" defaultValue={item?.result??"Neutro"}>{results.map(x=><option key={x}>{x}</option>)}</select></label><label className="full">Assunto<input name="subject" defaultValue={item?.subject} required/></label><label className="full">Descrição<textarea name="description" defaultValue={item?.description} rows={5}/></label><label>Próxima ação<input name="nextAction" defaultValue={item?.nextAction}/></label><label>Data da próxima ação<input type="date" name="nextActionDate" defaultValue={item?.nextActionDate}/></label></div><p className="form-hint">Os anexos serão disponibilizados quando o armazenamento seguro de documentos estiver configurado.</p><div className="form-actions"><button type="button" onClick={onCancel}>Cancelar</button><button className="primary">{item?"Guardar interação":"Registar interação"}</button></div></form>}
