"use client";

import { useEffect, useMemo, useState } from "react";
import type { Session } from "@supabase/supabase-js";
import { supabase } from "./supabase";

type User={id:string;name:string;email:string;role:"admin"|"commercial"};
type Client={id?:string;name:string;code:string;last?:string;owner?:string;assignedUserId:string};
type Activity={id:string;title:string;type:string;kind:string;status:string;startAt:string;occurredAt:string;assignedId:string;clientId:string;client:string;summary:string;manufacturerId?:string;manufacturer?:string};
type Task={id:string;title:string;status:string;priority:number;dueAt:string;assigneeId:string;clientId:string;client:string};
type Opportunity={id:string;title:string;value:number;probability:number;updatedAt:string;sellerId:string;clientId:string;client:string;stage:string;terminal:boolean};
type Manufacturer={id:string;name:string;updatedAt:string;terms:Array<{valid_until?:string;updated_at?:string}>};

const dateKey=(value:Date|string)=>{const d=new Date(value);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
const money=(value:number)=>new Intl.NumberFormat("pt-PT",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(value);
const isDone=(status:string)=>["completed","done","concluida","concluída","cancelled"].includes(status.toLowerCase());
const startOfWeek=(d:Date)=>{const x=new Date(d);const day=(x.getDay()+6)%7;x.setHours(0,0,0,0);x.setDate(x.getDate()-day);return x};

export default function OperationalDashboard({currentUser,session,clients,navigate,openClient,openManufacturer}:{currentUser:User;session:Session;clients:Client[];navigate:(section:string,params?:Record<string,string>)=>void;openClient:(client:any)=>void;openManufacturer:(id:string)=>void}){
  const initialParams=new URLSearchParams(typeof window==="undefined"?"":window.location.search);const [period,setPeriod]=useState<"week"|"month">(initialParams.get("period")==="month"?"month":"week");const [owner,setOwner]=useState(currentUser.role==="admin"?(initialParams.get("owner")??"all"):session.user.id);const [profiles,setProfiles]=useState<Array<{id:string;name:string}>>([]);const [activities,setActivities]=useState<Activity[]>([]);const [tasks,setTasks]=useState<Task[]>([]);const [opportunities,setOpportunities]=useState<Opportunity[]>([]);const [manufacturers,setManufacturers]=useState<Manufacturer[]>([]);const [loading,setLoading]=useState(true);const [notice,setNotice]=useState("");
  const load=async()=>{setLoading(true);const [profilesResult,activitiesResult,tasksResult,opportunitiesResult,manufacturersResult]=await Promise.all([
    supabase.from("profiles").select("id,full_name").eq("active",true),
    supabase.from("activities").select("id,title,summary,kind,interaction_type,status,start_at,occurred_at,assigned_to,actor_id,client_id,manufacturer_id,clients(trade_name),manufacturers(name)").order("occurred_at",{ascending:false}).limit(500),
    supabase.from("tasks").select("id,title,status,priority,due_at,assignee_id,client_id,clients(trade_name)").order("due_at").limit(300),
    supabase.from("opportunities").select("id,title,estimated_value,probability,updated_at,seller_id,client_id,clients(trade_name),opportunity_stages(name,terminal)").order("updated_at",{ascending:false}).limit(300),
    supabase.from("manufacturers").select("id,name,updated_at,manufacturer_commercial_terms(valid_until,updated_at)").is("deleted_at",null).eq("active",true).order("name")
  ]);const error=activitiesResult.error||tasksResult.error||opportunitiesResult.error||manufacturersResult.error;if(error)setNotice(error.message);
    setProfiles((profilesResult.data??[]).map((x:any)=>({id:x.id,name:x.full_name})));
    setActivities((activitiesResult.data??[]).map((x:any)=>({id:x.id,title:x.title??x.summary??"Atividade",summary:x.summary??x.title??"Atividade",type:x.interaction_type??x.kind??"Atividade",kind:x.kind??"note",status:x.status??"scheduled",startAt:x.start_at??x.occurred_at,occurredAt:x.occurred_at??x.start_at,assignedId:x.assigned_to??x.actor_id,clientId:x.client_id,client:x.clients?.trade_name??"Cliente",manufacturerId:x.manufacturer_id,manufacturer:x.manufacturers?.name})));
    setTasks((tasksResult.data??[]).map((x:any)=>({id:x.id,title:x.title,status:x.status,priority:x.priority??3,dueAt:x.due_at,assigneeId:x.assignee_id,clientId:x.client_id,client:x.clients?.trade_name??"Cliente"})));
    setOpportunities((opportunitiesResult.data??[]).map((x:any)=>({id:x.id,title:x.title,value:Number(x.estimated_value??0),probability:x.probability??0,updatedAt:x.updated_at,sellerId:x.seller_id,clientId:x.client_id,client:x.clients?.trade_name??"Cliente",stage:x.opportunity_stages?.name??"Sem fase",terminal:Boolean(x.opportunity_stages?.terminal)})));
    setManufacturers((manufacturersResult.data??[]).map((x:any)=>({id:x.id,name:x.name,updatedAt:x.updated_at,terms:x.manufacturer_commercial_terms??[]})));setLoading(false)};
  useEffect(()=>{load();const channel=supabase.channel("dashboard-live").on("postgres_changes",{event:"*",schema:"public"},()=>load()).subscribe();return()=>{supabase.removeChannel(channel)}},[session.user.id]);
  useEffect(()=>{if(currentUser.role!=="admin")setOwner(session.user.id)},[currentUser.role,session.user.id]);
  const now=new Date();const today=dateKey(now);const from=period==="week"?startOfWeek(now):new Date(now.getFullYear(),now.getMonth(),1);const until=period==="week"?new Date(from.getTime()+7*86400000):new Date(now.getFullYear(),now.getMonth()+1,1);
  const ownerMatches=(id:string)=>owner==="all"||id===owner;const selectedOwnerName=profiles.find(x=>x.id===owner)?.name??"";
  const periodActivities=activities.filter(x=>{const d=new Date(x.startAt||x.occurredAt);return d>=from&&d<until&&ownerMatches(x.assignedId)});
  const visibleTasks=tasks.filter(x=>ownerMatches(x.assigneeId));const activityTasks=activities.filter(x=>x.kind==="task"&&ownerMatches(x.assignedId));
  const pendingTasks=[...visibleTasks.filter(x=>!isDone(x.status)),...activityTasks.filter(x=>!isDone(x.status)).map(x=>({id:x.id,title:x.title,status:x.status,priority:3,dueAt:x.startAt,assigneeId:x.assignedId,clientId:x.clientId,client:x.client}))].filter((x,i,a)=>a.findIndex(y=>y.id===x.id)===i);
  const activeOpportunities=opportunities.filter(x=>!x.terminal&&ownerMatches(x.sellerId));const todayActivities=activities.filter(x=>dateKey(x.startAt)===today&&ownerMatches(x.assignedId)&&!isDone(x.status)).sort((a,b)=>+new Date(a.startAt)-+new Date(b.startAt));
  const visits=periodActivities.filter(x=>x.kind==="visit"||x.type.toLowerCase().includes("visita"));const completedPeriodTasks=[...visibleTasks.filter(x=>x.dueAt&&new Date(x.dueAt)>=from&&new Date(x.dueAt)<until&&isDone(x.status)),...periodActivities.filter(x=>x.kind==="task"&&isDone(x.status)).map(x=>({id:x.id,title:x.title,status:x.status,priority:3,dueAt:x.startAt,assigneeId:x.assignedId,clientId:x.clientId,client:x.client}))];
  const overdue=pendingTasks.filter(x=>x.dueAt&&new Date(x.dueAt)<now);const recentCutoff=now.getTime()-60*86400000;const lastByClient=new Map<string,number>();activities.forEach(x=>lastByClient.set(x.clientId,Math.max(lastByClient.get(x.clientId)??0,+new Date(x.occurredAt))));opportunities.forEach(x=>lastByClient.set(x.clientId,Math.max(lastByClient.get(x.clientId)??0,+new Date(x.updatedAt))));const noContact=clients.filter(x=>(lastByClient.get(x.id??"")??0)<recentCutoff&&(owner==="all"||x.owner?.toLowerCase().startsWith(selectedOwnerName.split(" ")[0]?.toLowerCase())));
  const staleOpportunities=activeOpportunities.filter(x=>+new Date(x.updatedAt)<now.getTime()-15*86400000);const staleTerms=manufacturers.filter(x=>x.terms.some(t=>t.valid_until&&new Date(t.valid_until)<now));const latestManufacturer=[...manufacturers].sort((a,b)=>+new Date(b.updatedAt)-+new Date(a.updatedAt))[0];const recent=activities.filter(x=>ownerMatches(x.assignedId)).slice(0,6);const stages=[...new Set(activeOpportunities.map(x=>x.stage))];
  const days=Array.from({length:period==="week"?7:Math.min(now.getDate(),31)},(_,i)=>{const d=new Date(from);d.setDate(d.getDate()+i);return d});const chart=days.map(d=>({d,visits:visits.filter(x=>dateKey(x.startAt)===dateKey(d)).length,tasks:completedPeriodTasks.filter(x=>dateKey(x.dueAt)===dateKey(d)).length}));const chartMax=Math.max(1,...chart.flatMap(x=>[x.visits,x.tasks]));
  const goActivity=(x:Activity)=>navigate("Agenda",{date:dateKey(x.startAt),activity:x.id});
  const preserveDashboardState=(nextPeriod:"week"|"month",nextOwner:string)=>{setPeriod(nextPeriod);setOwner(nextOwner);const params=new URLSearchParams();params.set("period",nextPeriod);if(nextOwner!=="all")params.set("owner",nextOwner);window.history.replaceState({},"",`/dashboard?${params}`)};
  return <><div className="page-title"><div><span>{new Intl.DateTimeFormat("pt-PT",{weekday:"long",day:"numeric",month:"long"}).format(now).toLocaleUpperCase("pt-PT")}</span><h1>Bom dia, {currentUser.name.split(" ")[0]}</h1></div><div className="dashboard-controls">{currentUser.role==="admin"&&<select aria-label="Responsável" value={owner} onChange={e=>preserveDashboardState(period,e.target.value)}><option value="all">Toda a equipa</option>{profiles.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>}<div className="period"><button className={period==="week"?"selected":""} onClick={()=>preserveDashboardState("week",owner)}>Esta semana</button><button className={period==="month"?"selected":""} onClick={()=>preserveDashboardState("month",owner)}>Este mês</button></div></div></div><p className="subtitle">Centro operacional da atividade comercial {currentUser.role==="admin"&&owner==="all"?"da equipa":"pessoal"}.</p>{notice&&<div className="email-notice">{notice}</div>}
  <div className="stats dashboard-stats"><button className="stat blue" onClick={()=>navigate("Agenda",{date:today,status:"in_progress"})}><span>Atividades hoje</span><strong>{todayActivities.length}</strong><small>{todayActivities.filter(x=>x.status==="in_progress").length} em curso</small></button><button className="stat amber" onClick={()=>navigate("Tarefas",{status:"open"})}><span>Tarefas pendentes</span><strong>{pendingTasks.length}</strong><small>{overdue.length} atrasadas</small></button><button className="stat green" onClick={()=>navigate("Oportunidades",{status:"open"})}><span>Pipeline aberto</span><strong>{money(activeOpportunities.reduce((s,x)=>s+x.value,0))}</strong><small>{activeOpportunities.length} oportunidades</small></button><button className="stat red" onClick={()=>navigate("Clientes",{withoutContact:"60"})}><span>Ação necessária</span><strong>{noContact.length}</strong><small>Clientes sem contacto há 60 dias</small></button></div>
  <section className="card dashboard-today"><div className="card-head"><h2>Hoje</h2><button onClick={()=>navigate("Agenda",{date:today})}>Ver agenda →</button></div>{todayActivities.length?<div className="today-list">{todayActivities.slice(0,6).map(x=><button key={x.id} onClick={()=>goActivity(x)}><time>{new Date(x.startAt).toLocaleTimeString("pt-PT",{hour:"2-digit",minute:"2-digit"})}</time><b>{x.type}</b><span>{x.client} — {x.title}</span></button>)}</div>:<div className="useful-empty">Não tem atividades agendadas para hoje.<button onClick={()=>navigate("Agenda",{date:today,new:"1"})}>＋ Agendar atividade</button></div>}</section>
  <div className="dashboard-grid"><section className="card wide"><div className="card-head"><h2>{period==="week"?"Atividade da semana":"Atividade do mês"}</h2><button onClick={()=>navigate("Relatórios",{period})}>Ver relatório →</button></div>{visits.length||completedPeriodTasks.length?<><div className="real-chart">{chart.map(x=><div className="bar-day" key={dateKey(x.d)}><div className="bars"><button aria-label={`Visitas ${dateKey(x.d)}`} style={{height:x.visits?`${x.visits/chartMax*100}%`:"0"}} onClick={()=>navigate("Visitas",{date:dateKey(x.d)})}/><button aria-label={`Tarefas concluídas ${dateKey(x.d)}`} style={{height:x.tasks?`${x.tasks/chartMax*100}%`:"0"}} onClick={()=>navigate("Tarefas",{status:"done",date:dateKey(x.d)})}/></div><span>{period==="week"?new Intl.DateTimeFormat("pt-PT",{weekday:"short"}).format(x.d):x.d.getDate()}</span></div>)}</div><div className="legend dashboard-legend"><button onClick={()=>navigate("Visitas",{from:dateKey(from),to:dateKey(until)})}><i className="dot blue"/>Visitas</button><button onClick={()=>navigate("Tarefas",{status:"done",from:dateKey(from),to:dateKey(until)})}><i className="dot green"/>Tarefas concluídas</button></div></>:<div className="useful-empty">Não existe atividade registada neste período.</div>}</section>
  <section className="card"><div className="card-head"><h2>Próximas visitas</h2><button onClick={()=>navigate("Agenda",{date:today,type:"Visita"})}>Ver agenda →</button></div>{activities.filter(x=>(x.kind==="visit"||x.type.toLowerCase().includes("visita"))&&new Date(x.startAt)>=now&&ownerMatches(x.assignedId)).slice(0,4).map(x=><button className="dashboard-line" key={x.id} onClick={()=>goActivity(x)}><time>{new Date(x.startAt).toLocaleString("pt-PT",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"})}</time><strong>{x.client}</strong><span>{x.title}</span></button>)}{!activities.some(x=>(x.kind==="visit"||x.type.toLowerCase().includes("visita"))&&new Date(x.startAt)>=now&&ownerMatches(x.assignedId))&&<div className="useful-empty">Não tem visitas agendadas.<button onClick={()=>navigate("Agenda",{date:today,new:"1",type:"Visita"})}>＋ Agendar visita</button></div>}</section>
  <section className="card wide"><div className="card-head"><h2>Tarefas prioritárias</h2><button onClick={()=>navigate("Tarefas",{status:"open"})}>Ver todas →</button></div>{pendingTasks.sort((a,b)=>(a.dueAt?+new Date(a.dueAt):Infinity)-(b.dueAt?+new Date(b.dueAt):Infinity)).slice(0,5).map(x=><button className={`dashboard-line task-dashboard-line ${x.dueAt&&new Date(x.dueAt)<now?"overdue":""}`} key={x.id} onClick={()=>navigate("Tarefas",{task:x.id})}><time>{x.dueAt?new Date(x.dueAt).toLocaleString("pt-PT",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}):"Sem prazo"}</time><strong>{x.title}</strong><span>{x.client}</span>{x.dueAt&&new Date(x.dueAt)<now&&<em>Atrasada</em>}</button>)}{!pendingTasks.length&&<div className="useful-empty">Não existem tarefas prioritárias.<button onClick={()=>navigate("Tarefas",{new:"1"})}>＋ Criar tarefa</button></div>}</section>
  <section className="card pipeline-dashboard" onClick={()=>navigate("Oportunidades",{status:"open"})}><div className="card-head"><h2>Pipeline</h2><button onClick={e=>{e.stopPropagation();navigate("Oportunidades",{status:"open"})}}>Ver oportunidades →</button></div><div className="pipeline-total"><div><span>Valor total do Pipeline</span><strong>{money(activeOpportunities.reduce((s,x)=>s+x.value,0))}</strong><small>{activeOpportunities.length} oportunidades</small></div><b>Ativo</b></div>{stages.map(stage=><button className="pipeline-stage-link" key={stage} onClick={e=>{e.stopPropagation();navigate("Oportunidades",{stage})}}><span>{stage}</span><strong>{activeOpportunities.filter(x=>x.stage===stage).length}</strong></button>)}{!activeOpportunities.length&&<div className="useful-empty">Nenhuma oportunidade em aberto.</div>}</section>
  <section className="card wide"><div className="card-head"><h2>A minha atenção</h2><span>Alertas operacionais</span></div><div className="attention-list"><button onClick={()=>navigate("Tarefas",{status:"overdue"})}><strong>{overdue.length} tarefas atrasadas</strong><span>Ver tarefas vencidas</span></button><button onClick={()=>navigate("Clientes",{withoutContact:"60"})}><strong>{noContact.length} clientes sem contacto</strong><span>Há mais de 60 dias</span></button><button onClick={()=>navigate("Oportunidades",{stale:"15"})}><strong>{staleOpportunities.length} oportunidades sem atividade</strong><span>Há mais de 15 dias</span></button></div></section>
  <section className="card"><div className="card-head"><h2>Fabricantes</h2><button onClick={()=>navigate("Fabricantes")}>Ver fabricantes →</button></div><button className="manufacturer-summary" onClick={()=>navigate("Fabricantes")}><strong>{manufacturers.length}</strong><span>fabricantes ativos</span><small>{staleTerms.length} condições com validade terminada</small></button>{latestManufacturer&&<button className="dashboard-line" onClick={()=>openManufacturer(latestManufacturer.id)}><time>Atualização recente</time><strong>{latestManufacturer.name}</strong><span>{new Date(latestManufacturer.updatedAt).toLocaleDateString("pt-PT")}</span></button>}</section>
  <section className="card wide"><div className="card-head"><h2>Atividade recente</h2><button onClick={()=>navigate("Agenda")}>Ver atividade →</button></div>{recent.map(x=><button className="dashboard-line" key={x.id} onClick={()=>goActivity(x)}><time>{new Date(x.occurredAt).toLocaleString("pt-PT")}</time><strong>{x.summary}</strong><span>{x.client}{x.manufacturer?` · ${x.manufacturer}`:""}</span></button>)}{!recent.length&&<div className="useful-empty">Ainda não existe atividade registada.</div>}</section>
  <section className="card"><div className="card-head"><h2>Ações rápidas</h2></div><div className="quick-actions"><button onClick={()=>navigate("Agenda",{new:"1",type:"Visita"})}>＋ Visita</button><button onClick={()=>navigate("Tarefas",{new:"1"})}>＋ Tarefa</button><button onClick={()=>navigate("Oportunidades",{new:"1"})}>＋ Oportunidade</button><button onClick={()=>navigate("Clientes",{new:"1"})}>＋ Cliente</button></div></section></div>{loading&&<span className="dashboard-loading">A atualizar dados…</span>}</>;
}
