"use client";
import { useEffect,useMemo,useState } from "react";
import type { Session } from "@supabase/supabase-js";
import { supabase } from "../supabase";
import { calculateSuccessiveDiscounts,formatDiscounts,parseDiscounts } from "../catalog-discounts";
import "./catalogo-beta.css";
import "./quantity.css";

type Client={id:string;name:string;contacts:Array<{id:string;name:string}>};
type Product={id:string;reference:string;ean?:string;designation:string;short_description?:string;main_image_url?:string;status:string;manufacturer_id:string;family_id?:string;catalog_product_families?:{name?:string;subfamily?:string};catalog_product_variants?:Array<{id:string;reference?:string;designation_suffix?:string;attributes:Record<string,string>}>;catalog_price_list_items?:Array<{list_price:number;currency:string}>};
type CartLine={key:string;product:Product;variantId?:string;variantLabel?:string;quantity:number;listPrice:number;automatic:number[];applied:number[];manual:boolean};
type CommercialRule={id:string;manufacturer_id:string;client_id?:string|null;family_id?:string|null;product_id?:string|null;variant_id?:string|null;discount_percentages:number[];special_price?:number|null;priority:number};
const money=(value:number)=>new Intl.NumberFormat("pt-PT",{style:"currency",currency:"EUR"}).format(value);

export default function CatalogoBeta(){
 const [session,setSession]=useState<Session|null>(null),[checking,setChecking]=useState(true),[allowed,setAllowed]=useState(false),[notice,setNotice]=useState("");
 const [clients,setClients]=useState<Client[]>([]),[products,setProducts]=useState<Product[]>([]),[rules,setRules]=useState<CommercialRule[]>([]),[clientId,setClientId]=useState(""),[contactId,setContactId]=useState(""),[manufacturerId,setManufacturerId]=useState(""),[query,setQuery]=useState(""),[family,setFamily]=useState(""),[status,setStatus]=useState(""),[cart,setCart]=useState<CartLine[]>([]),[drafts,setDrafts]=useState<Array<{id:string;order_number:string;total:number;updated_at:string}>>([]),[saving,setSaving]=useState(false),[mobileCart,setMobileCart]=useState(false);
 useEffect(()=>{supabase.auth.getSession().then(async({data})=>{const active=data.session;setSession(active);if(!active){setChecking(false);return}const {data:access}=await supabase.rpc("has_catalog_orders_beta_access");setAllowed(access===true);setChecking(false);if(access===true)await loadBase(active.user.id)})},[]);
 useEffect(()=>{const link=document.querySelector<HTMLAnchorElement>(".beta-catalog>header>a");if(link)link.href="/dashboard";const label=document.querySelector<HTMLElement>(".beta-catalog>header div>span");if(label)label.textContent="CATÁLOGO B2B"},[allowed]);
 const loadBase=async(userId:string)=>{const [{data:clientRows},{data:productRows},{data:ruleRows},{data:draftRows}]=await Promise.all([
  supabase.from("clients").select("id,trade_name,client_contacts(id,first_name,last_name)").order("trade_name"),
  supabase.from("catalog_products").select("id,reference,ean,designation,short_description,main_image_url,status,manufacturer_id,family_id,catalog_product_families(name,subfamily),catalog_product_variants(id,reference,designation_suffix,attributes),catalog_price_list_items(list_price,currency,valid_from,valid_until)").eq("active",true).order("designation"),
  supabase.from("catalog_commercial_rules").select("id,manufacturer_id,client_id,family_id,product_id,variant_id,discount_percentages,special_price,priority").eq("active",true).order("priority",{ascending:true}),
  supabase.from("catalog_orders").select("id,order_number,total,updated_at").eq("created_by",userId).eq("status","draft").order("updated_at",{ascending:false})]);
  setClients((clientRows??[]).map((c:any)=>({id:c.id,name:c.trade_name,contacts:(c.client_contacts??[]).map((x:any)=>({id:x.id,name:[x.first_name,x.last_name].filter(Boolean).join(" ")}))})));
  setProducts((productRows??[]) as Product[]);setRules((ruleRows??[]) as CommercialRule[]);setDrafts(draftRows??[]);const first=(productRows??[])[0];if(first)setManufacturerId(first.manufacturer_id)
 };
 const automaticFor=(product:Product,variantId?:string)=>{const matching=rules.filter(r=>r.manufacturer_id===product.manufacturer_id&&(!r.client_id||r.client_id===clientId)&&(!r.family_id||r.family_id===product.family_id)&&(!r.product_id||r.product_id===product.id)&&(!r.variant_id||r.variant_id===variantId));const scored=matching.sort((a,b)=>{const specificity=(r:CommercialRule)=>Number(Boolean(r.client_id))*16+Number(Boolean(r.variant_id))*8+Number(Boolean(r.product_id))*4+Number(Boolean(r.family_id))*2;return specificity(b)-specificity(a)||a.priority-b.priority});return (scored[0]?.discount_percentages??[]).map(Number)};
 const selectedClient=clients.find(x=>x.id===clientId);const families=[...new Set(products.map(x=>x.catalog_product_families?.name).filter(Boolean))] as string[];
 const visible=useMemo(()=>products.filter(p=>p.manufacturer_id===manufacturerId&&(!family||p.catalog_product_families?.name===family)&&(!status||p.status===status)&&`${p.reference} ${p.ean??""} ${p.designation} ${p.short_description??""} ${p.catalog_product_families?.name??""}`.toLowerCase().includes(query.toLowerCase())),[products,manufacturerId,family,status,query]);
 const add=(product:Product,variantId?:string,quantity=1)=>{const safeQuantity=Math.max(1,Math.floor(quantity||1)),price=Number(product.catalog_price_list_items?.[0]?.list_price??0),variant=product.catalog_product_variants?.find(x=>x.id===variantId),key=`${product.id}:${variantId??""}`,automatic=automaticFor(product,variantId);setCart(rows=>{const found=rows.find(x=>x.key===key);return found?rows.map(x=>x.key===key?{...x,quantity:x.quantity+safeQuantity}:x):[...rows,{key,product,variantId,variantLabel:variant?.designation_suffix,quantity:safeQuantity,listPrice:price,automatic,applied:automatic,manual:false}]})};
 const updateDiscount=(key:string,value:string)=>setCart(rows=>rows.map(x=>x.key===key?{...x,applied:parseDiscounts(value),manual:formatDiscounts(parseDiscounts(value))!==formatDiscounts(x.automatic)}:x));
 const subtotal=cart.reduce((sum,line)=>sum+calculateSuccessiveDiscounts(line.listPrice,line.applied).netPrice*line.quantity,0);
 const saveDraft=async()=>{if(!session||!clientId||!manufacturerId||!cart.length){setNotice("Selecione cliente, fabricante e pelo menos um produto.");return}setSaving(true);setNotice("");const now=new Date().toISOString(),number=`BETA-${Date.now()}`;const order=await supabase.from("catalog_orders").insert({order_number:number,client_id:clientId,contact_id:contactId||null,manufacturer_id:manufacturerId,status:"draft",seller_id:session.user.id,created_by:session.user.id,currency:"EUR",subtotal,total:subtotal,updated_at:now}).select("id,order_number,total,updated_at").single();if(order.error){setNotice(order.error.message);setSaving(false);return}const lines=cart.map(line=>{const calc=calculateSuccessiveDiscounts(line.listPrice,line.applied);return {order_id:order.data.id,product_id:line.product.id,variant_id:line.variantId||null,reference_snapshot:line.product.reference,designation_snapshot:line.product.designation+(line.variantLabel?` — ${line.variantLabel}`:""),quantity:line.quantity,list_price_snapshot:line.listPrice,automatic_discounts:line.automatic,applied_discounts:line.applied,net_unit_price:calc.netPrice,line_total:calc.netPrice*line.quantity,discount_manually_changed:line.manual,discount_changed_by:line.manual?session.user.id:null,discount_changed_at:line.manual?now:null}});const saved=await supabase.from("catalog_order_lines").insert(lines);if(saved.error){setNotice(saved.error.message)}else{setNotice(`Rascunho ${number} guardado.`);setDrafts(rows=>[order.data,...rows]);setCart([])}setSaving(false)};
 const reopen=async(id:string)=>{const [{data:order},{data}]=await Promise.all([supabase.from("catalog_orders").select("client_id,contact_id,manufacturer_id").eq("id",id).single(),supabase.from("catalog_order_lines").select("product_id,variant_id,quantity,list_price_snapshot,automatic_discounts,applied_discounts,discount_manually_changed,catalog_products(*),catalog_product_variants(designation_suffix)").eq("order_id",id)]);if(order){setClientId(order.client_id);setContactId(order.contact_id??"");setManufacturerId(order.manufacturer_id)}setCart((data??[]).map((x:any)=>({key:`${x.product_id}:${x.variant_id??""}`,product:x.catalog_products,variantId:x.variant_id??undefined,variantLabel:x.catalog_product_variants?.designation_suffix,quantity:Number(x.quantity),listPrice:Number(x.list_price_snapshot),automatic:(x.automatic_discounts??[]).map(Number),applied:(x.applied_discounts??[]).map(Number),manual:x.discount_manually_changed})));setMobileCart(true)};
 if(checking)return <main className="beta-gate"><p>A validar acesso…</p></main>;
 if(!session)return <main className="beta-gate"><h1>Acesso reservado</h1><p>Inicie sessão no CRM para continuar.</p><a href="/">Voltar ao CRM</a></main>;
 if(!allowed)return <main className="beta-gate"><h1>Página não disponível</h1><p>Esta funcionalidade não está ativa para a sua conta.</p><a href="/">Voltar ao CRM</a></main>;
 return <main className="beta-catalog"><header><a href="/">← CRM</a><div><span>BETA PRIVADO</span><h1>Catálogo & Encomendas</h1></div><button onClick={()=>setMobileCart(true)}>Encomenda · {cart.length}</button></header><section className="beta-setup"><label>Cliente<select value={clientId} onChange={e=>{setClientId(e.target.value);setContactId("")}}><option value="">Selecionar cliente</option>{clients.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Contacto<select value={contactId} onChange={e=>setContactId(e.target.value)} disabled={!clientId}><option value="">Sem contacto específico</option>{selectedClient?.contacts.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Fabricante<select value={manufacturerId} onChange={e=>setManufacturerId(e.target.value)}>{[...new Map(products.map(p=>[p.manufacturer_id,"ACHA Herramientas"])).entries()].map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label></section>{notice&&<div className="beta-notice">{notice}</div>}<div className="beta-layout"><aside className="beta-filters"><h2>Filtros</h2><input placeholder="Referência, produto, EAN…" value={query} onChange={e=>setQuery(e.target.value)}/><select value={family} onChange={e=>setFamily(e.target.value)}><option value="">Todas as famílias</option>{families.map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos os estados</option><option value="active">Ativo</option><option value="on_request">Sob consulta</option><option value="discontinued">Descontinuado</option></select><h3>Rascunhos</h3>{drafts.map(x=><button key={x.id} onClick={()=>reopen(x.id)}><strong>{x.order_number}</strong><span>{money(Number(x.total))}</span></button>)}</aside><section className="beta-products"><div className="beta-results"><strong>{visible.length} produtos</strong><span>Condições comerciais aplicadas automaticamente</span></div><div className="product-grid">{visible.map(p=><ProductCard key={p.id} product={p} add={add} discounts={automaticFor(p)}/>)}</div></section><OrderSummary open={mobileCart} close={()=>setMobileCart(false)} cart={cart} setCart={setCart} updateDiscount={updateDiscount} subtotal={subtotal} save={saveDraft} saving={saving}/></div><button className="mobile-cart" onClick={()=>setMobileCart(true)}>Ver encomenda · {cart.length} · {money(subtotal)}</button></main>
}
function ProductCard({product,add,discounts}:{product:Product;add:(p:Product,v?:string,q?:number)=>void;discounts:number[]}){const [variant,setVariant]=useState(product.catalog_product_variants?.[0]?.id??""),[quantity,setQuantity]=useState(1);const price=Number(product.catalog_price_list_items?.[0]?.list_price??0),net=calculateSuccessiveDiscounts(price,discounts).netPrice;return <article className="product-card"><div className="product-image">{product.main_image_url?<img src={product.main_image_url} alt=""/>:<span>Sem imagem</span>}</div><small>{product.reference}</small><h2>{product.designation}</h2><p>{product.short_description}</p><dl><div><dt>PVP</dt><dd>{money(price)}</dd></div><div><dt>Desconto</dt><dd>{formatDiscounts(discounts)||"—"}</dd></div><div className="net"><dt>Preço líquido</dt><dd>{money(net)}</dd></div></dl>{product.catalog_product_variants?.length?<select value={variant} onChange={e=>setVariant(e.target.value)}>{product.catalog_product_variants.map(x=><option key={x.id} value={x.id}>{x.designation_suffix||x.reference}</option>)}</select>:<span className="no-variant">Sem variantes</span>}<label className="product-quantity">Quantidade a encomendar<input type="number" min="1" step="1" value={quantity} onChange={e=>setQuantity(Math.max(1,Number(e.target.value)||1))}/></label><button onClick={()=>add(product,variant||undefined,quantity)}>Adicionar {quantity} à encomenda</button></article>}
function OrderSummary({open,close,cart,setCart,updateDiscount,subtotal,save,saving}:{open:boolean;close:()=>void;cart:CartLine[];setCart:(value:CartLine[]|((rows:CartLine[])=>CartLine[]))=>void;updateDiscount:(k:string,v:string)=>void;subtotal:number;save:()=>void;saving:boolean}){return <aside className={`order-summary ${open?"open":""}`}><div className="order-head"><div><span>RASCUNHO</span><h2>Resumo da encomenda</h2></div><button onClick={close}>×</button></div>{cart.map(line=>{const calc=calculateSuccessiveDiscounts(line.listPrice,line.applied);return <article key={line.key}><strong>{line.product.designation}</strong><small>{line.product.reference}{line.variantLabel?` · ${line.variantLabel}`:""}</small><div className="qty"><button onClick={()=>setCart(rows=>rows.map(x=>x.key===line.key?{...x,quantity:Math.max(1,x.quantity-1)}:x))}>−</button><b>{line.quantity}</b><button onClick={()=>setCart(rows=>rows.map(x=>x.key===line.key?{...x,quantity:x.quantity+1}:x))}>+</button><button className="remove" onClick={()=>setCart(rows=>rows.filter(x=>x.key!==line.key))}>Remover</button></div><label>Desconto<input defaultValue={formatDiscounts(line.applied)} onBlur={e=>updateDiscount(line.key,e.target.value)} aria-label={`Desconto ${line.product.designation}`}/></label><div className="line-total"><span>{money(calc.netPrice)} × {line.quantity}</span><strong>{money(calc.netPrice*line.quantity)}</strong></div>{line.manual&&<em>Desconto alterado manualmente</em>}</article>})}{!cart.length&&<p className="empty-cart">A encomenda ainda não tem produtos.</p>}<footer><div><span>Subtotal</span><strong>{money(subtotal)}</strong></div><button disabled={saving||!cart.length} onClick={save}>{saving?"A guardar…":"Guardar como rascunho"}</button></footer></aside>}

